-- Role
INSERT INTO SYS_ROLE(id,name) VALUES (1,'ROLE_ADMIN');
INSERT INTO SYS_ROLE(id,name) VALUES (2,'ROLE_CUSTOMER');
INSERT INTO SYS_ROLE(id,name) VALUES (3,'ROLE_PHOTOGRAPHER');
INSERT INTO SYS_ROLE(id,name) VALUES (4,'ROLE_BECOME_PHOTOGRAPHER');